esphome:
  name: sinkmate

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "sinkmate"

ota:
  password: "sinkmate"

wifi:
  ssid: "iPhone"
  password: "benjamin"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sinkmate Fallback Hotspot"
    password: "ks0R9p1oTwJk"

captive_portal:

switch:
  - platform: gpio
    pin: D4
    name: "LED"
    inverted: true
  - platform: gpio
    pin: 14
    name: "Valve"
    on_turn_off:
      then:
      - pulse_meter.set_total_pulses:
          id: flow_sensor
          value: 0
    on_turn_on:
      then:
      - pulse_meter.set_total_pulses:
          id: flow_sensor
          value: 0
    
sensor:
  - platform: pulse_meter
    pin: 12
    name: "FlowSensor"
    id: flow_sensor
    timeout: 1.5 min
    total:
      name: "Total"
      accuracy_decimals: 1